# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba270d6c28c8f636bf7a546497a4756474053cc868c860374d6e4b73d696db6ff01be67c0bd6565eb44e2def3bd05897bf379838082b3d149e3439741f516fbb

test:
  secret_key_base: 8dddee251ceed7059ce889f8ac5abb87ab6e4bb8f05193dfafd563b4341590b59dff55feddee992174174eac873a47117bd63096f690f7becd67945f2394ce8d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
